hello: Hello
error_text: Invalid command
working: Its working..
completed: Completed
upscaling: Upscaling...
progress: "Progress: {progress}\nETA: {eta} "
current_negative_prompt: Current negative prompt - {prompt}
current_steps: Current steps - {steps}
current_model: Current model - {model}
current_size: Current img size - {width}x{height}
current_show_progress: Current show_progress - {show_progress}
current_show_progress_preview: Current show_progress_preview - {show_progress_preview}
current_img2img_denoising_strength: Current img2img denoising strength - {img2img_denoising_strength}
config_header: ==== Bot config ====
config_entry: |-
  {type} {code}
  - {description}
  - {value}
change_config_button: Change - {code}
change_config_msg: |-
  Changing {type} {code}
  Enter new value
  Cancel - /cancel, empty - /empty
change_config_success: Changing success
change_config_error: Changing error
config_saved: Config saved!
config_reseted: Config reseted!
error: Я упал
help: |-
  /anime 
  /steps <step_num>
  /size <width> <height> 
  - For img2img generating frame will be resized to fit in setting bounds.
  - ex. Size = 512x512. 
  - Incoming - 1024x512. 
  - Generated - 512x256
  /negative <text>
  /img2img [denoising] [steps] [prompt]
  /model
  /show_progress_preview<True|False or 0|1>
  /show_progress <True|False or 0|1>
  /upscale (Send as caption for image)"